name: Selenium CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      # ---- Checkout Repo ----
      - name: Checkout code
        uses: actions/checkout@v4

      # ---- Install Python ----
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ---- Install Google Chrome ----
      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      # ---- Install Dependencies ----
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-html selenium webdriver-manager

      # ---- Run Tests ----
      - name: Run Selenium tests
        run: |
          pytest -q --html=reports/report.html

      # ---- Upload HTML Report ----
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/report.html

      # ---- Upload Screenshots ----
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/
